profile: full
ceip_policy_disclosed: true # Installation fails if this is not set to true. Not a string.
buildservice:
  kp_default_repository: #
  kp_default_repository_username: #
  kp_default_repository_password: #
  tanzunet_username: #
  tanzunet_password: #
  enable_automatic_dependency_updates: true
  descriptor_name: full

supply_chain: basic

cnrs:
  domain_name: onlyeh.com

ootb_supply_chain_basic:
  registry:
    server: #
    repository: #
  gitops:
    ssh_secret: ""

learningcenter:
  ingressDomain: "DOMAIN-NAME"

tap_gui:
  service_type: LoadBalancer
  ingressEnabled: "true"
  ingressDomain: "onlytap.info"
  app_config:
    app:
      baseUrl: http://tap-gui.onlytap.info
    catalog:
      locations:
        - type: url
          target: https://GIT-CATALOG-URL/catalog-info.yaml
    backend:
      baseUrl: http://tap-gui.onlytap.info
      cors:
        origin: http://tap-gui.onlytap.info

contour:
  infrastructure_provider: aws
  envoy:
    service:
      
